version: "3"
services:
  php:
    # імʼя контейнеру, яке будемо використовувати при вході на контейнер
    container_name: php_app_2
    build:
      context: ./
      # посилання на докерфайл з налаштуванням контейнеру
      dockerfile: "docker-configs/php/Dockerfile"
    # встановлюємо змінні оточення
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    # прописуємо синхронізацію директорій
    volumes:
      - ./:/srv/src/hillelpro

  nginx:
    container_name: php_server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php


